#########
# PROJECT
#########

# Replace the values here with your project` information.
project:
  # The name of the organisation or entity that owns this project
  organisation: "Electric Book Works"
  # A live web address for the organisation
  url: "http://electricbook.works/"
  # The default contact email address
  email: "support@electricbook.works"
  # The name of the project of books in this folder.
  name: "Electric Book"
  # A one-liner about this project. Useful for Open Graph metadata.
  description: "The Electric Book template in action."
  # The logo of the organisation, saved web-ready in /assets
  logo: "publisher-logo.jpg"
  # An image in /assets that stands for the project
  image: "cover.jpg"
  # Credit line, by default in the footer, overidden in locales.yml
  credit: "Built with the [Electric Book](http://electricbook.works)"
  # Primary language code for this project as a whole
  language: "en"
  # App bundle ID unique across all app stores
  app-id: com.example.myapp
  # Version. You must change this with each app update
  version: "1.0.0"


########
# TITLES
########

## Metadata follows [Dublin Core](https://en.wikipedia.org/wiki/Dublin_Core#DCMI_Metadata_Terms)
## Custom fields added to standard DC terms: subtitle, publisher URL
## When listing files, exlude file extensions, and surround them in quotes
## especially if they contain only numbers.

works:
  - directory: "book"
    title: "Shades of green"
    subtitle: "Reimagining philanthropy"
    creator: "The Shuttleworth Foundation, Adam Hyde, Chris McGivern, Helen Turvey, Jason Hudson, Jesse Von Doom, Karien Bezuidenhout, Kathi Fletcher, Sean Bonner" # E.g. the author
    contributor: "" # E.g. other contributors
    subject: "Business writing, Philanthropy & Charity" # E.g. BISAC terms (https://bisg.org/page/BISACEdition) or BIC (http://editeur.dyndns.org/bic_categories)
    description: "This book explores and documents the philosophy, motivation and learning behind the Shuttleworth Foundation and its Fellowship community." # E.g. the blurb
    publisher: "The Shuttleworth Foundation" # E.g. the publisher, imprint or brand name
    publisher-url: "https://www.shuttleworthfoundation.org/"
    date: "" # YYYY-MM-DD e.g. publication date
    modified: "" # YYYY-MM-DD e.g. date of last revision
    type: "Non-fiction" # e.g. Novel, Poetry, Memoir
    identifier: "978-1-694-49711-6" # e.g. ISBN or UUID
    source: "" # e.g. parent ISBN or ISTC
    language: "en" # use ISO 639-1, 639-2, or 639-3 codes (in that order of preference)
    relation: "" # e.g. other edition ISBN
    coverage: "" # e.g. geographic place or chronological time span
    rights: "Creative Commons Attribution-Share Alike License" # e.g. a copyright statement
    image: "cover.jpg"
    products: # Metadata for each product for this title (only use values that override parent metadata)
      print-pdf: 
        date: "" # YYYY-MM-DD e.g. publication or creation date
        format: "Print" # e.g. Paperback, Digital download, Digital online
        identifier: "" # e.g. ISBN or UUID
        image: "cover.jpg"
        files:
          - "0-1-titlepage"
          - "0-2-copyright"
          - "0-3-contents"
          - "0-4-about"
          - "01-00"
          - "01-01"
          - "01-02"
          - "01-03"
          - "01-04"
          - "01-05"
          - "02-00"
          - "02-06"
          - "02-07"
          - "02-08"
          - "02-09"
          - "03-00"
          - "03-10"
          - "03-11"
          - "03-12"
          - "03-13"
          - "03-14"
          - "04-00"
          - "04-15"
          - "04-16"
          - "04-17"
          - "05-00"
          - "05-18"
          - "06-00"
          - "06-19"
          - "50-00-appendix-opener"
          - "50-01-appendix"
          - "50-02-references"
        toc: # For each menu item, include at least label and file. Optionally add id (for deep linking) and children.
          - label: "Reconsider everything"
            id: "1-reconsider-everything"
            children: 
              - label: "**01.** Our stance"
                file: "01-01"
                id: "01-our-stance"
              - label: "**02.** Our story, our principles"
                file: "01-02"
                id: "02-our-story-our-principles"
              - label: "**03.** In practice"
                file: "01-03"
                id: "03-in-practice"
              - label: "**04.** With people"
                file: "01-04"
                id: "04-with-people"
              - label: "**05.** Through open"
                file: "01-05"
                id: "05-through-open"
          - label: "Towards a shared power"
            id: "2-towards-a-shared-power"
            children: 
              - label: "**06.** Sharing power"
                file: "02-06"
                id: "06-sharing-power"
              - label: "**07.** Open is power"
                file: "02-07"
                id: "07-open-is-power"
              - label: "**08.** Culture of community"
                file: "02-08"
                id: "08-culture-of-community"
              - label: "**09.** Community means co-ownership"
                file: "02-09"
                id: "09-community-means-coownership"
          - label: "True fellowship"
            id: "3-true-fellowship"
            children: 
              - label: "**10.** Who is a fellow?"
                file: "03-10"
                id: "10-who-is-a-fellow"
              - label: "**11.** Connecting"
                file: "03-11"
                id: "11-connecting"
              - label: "**12.** Reaching agreement"
                file: "03-12"
                id: "12-reaching-agreement"
              - label: "**13.** Working together"
                file: "03-13"
                id: "13-working-together"
              - label: "**14.** Taking the long view"
                file: "03-14"
                id: "14-taking-the-long-view"
          - label: "Nurturing community"
            id: "4-nurturing-community"
            children: 
              - label: "**15.** A marriage of misfits"
                file: "04-15"
                id: "15-a-marriage-of-misfits"
              - label: "**16.** Gathering together"
                file: "04-16"
                id: "16-gathering-together"
              - label: "**17.** Once a fellow, always a fellow"
                file: "04-17"
                id: "17-once-a-fellow-always-a-fellow"
          - label: "Funding the future"
            id: "5-funding-the-future"
            children: 
              - label: "**18.** The $5m challenge"
                file: "05-18"
                id: "18-the-$5m-challenge"
          - label: "Epilogue"
            id: "6-epilogue"
            children: 
              - label: "**19.** Shades of green"
                file: "06-19"
                id: "19-shades-of-green"
          - label: "Appendix"
            children:
              - label: "Overview"
                file: "50-01-appendix"
                id: "overview"
              - label: "**i.** Application form"
                file: "50-01-appendix"
                id: "i-application-form"
              - label: "**ii.** The agreement letter"
                file: "50-01-appendix"
                id: "ii-the-agreement-letter"
              - label: "**iii.** Open requirements"
                file: "50-01-appendix"
                id: "iii-open-requirements"
              - label: "**iv.** Open Locks"
                file: "50-01-appendix"
                id: "iv-open-locks"
              - label: "**v.** Gathering guidelines"
                file: "50-01-appendix"
                id: "v-gathering-guidelines"
              - label: "**vi.** Thou shalt scale sustainably"
                file: "50-01-appendix"
                id: "vi-though-shalt-scale-sustainably"
          - label: "References"
            file: "50-02-references"
      web:
        date: "" # YYYY-MM-DD e.g. publication date or last revision
        format: "Digital online" # e.g. Paperback, Digital download, Digital online
        identifier: "" # e.g. ISBN or UUID
        image: "cover.jpg"
        files:
          - "index"
          - "0-1-titlepage"
          - "0-2-copyright"
          - "0-3-contents"
          - "0-4-about"
          # - "01-00"
          - "01-01"
          - "01-02"
          - "01-03"
          - "01-04"
          - "01-05"
          # - "02-00"
          - "02-06"
          - "02-07"
          - "02-08"
          - "02-09"
          # - "03-00"
          - "03-10"
          - "03-11"
          - "03-12"
          - "03-13"
          - "03-14"
          # - "04-00"
          - "04-15"
          - "04-16"
          - "04-17"
          # - "05-00"
          - "05-18"
          # - "06-00"
          - "06-19"
          # - "50-00-appendix-opener"
          - "50-01-appendix"
          - "50-02-references"
        nav: # For each menu item, include at least label and file. Optionally add id (for deep linking) and children.
          - label: "Frontmatter"
            children:
              - label: "Cover"
                file: "index"
              - label: "Title page"
                file: "0-1-titlepage"
              - label: "Copyright"
                file: "0-2-copyright"
          - label: "Contents"
            file: "0-3-contents"
          - label: "Reconsider everything"
            id: "1-reconsider-everything"
            children: 
              - label: "**01.** Our stance"
                file: "01-01"
                id: "01-our-stance"
              - label: "**02.** Our story, our principles"
                file: "01-02"
                id: "02-our-story-our-principles"
              - label: "**03.** In practice"
                file: "01-03"
                id: "03-in-practice"
              - label: "**04.** With people"
                file: "01-04"
                id: "04-with-people"
              - label: "**05.** Through open"
                file: "01-05"
                id: "05-through-open"
          - label: "Towards a shared power"
            id: "2-towards-a-shared-power"
            children: 
              - label: "**06.** Sharing power"
                file: "02-06"
                id: "06-sharing-power"
              - label: "**07.** Open is power"
                file: "02-07"
                id: "07-open-is-power"
              - label: "**08.** Culture of community"
                file: "02-08"
                id: "08-culture-of-community"
              - label: "**09.** Community means co-ownership"
                file: "02-09"
                id: "09-community-means-coownership"
          - label: "True fellowship"
            id: "3-true-fellowship"
            children: 
              - label: "**10.** Who is a fellow?"
                file: "03-10"
                id: "10-who-is-a-fellow"
              - label: "**11.** Connecting"
                file: "03-11"
                id: "11-connecting"
              - label: "**12.** Reaching agreement"
                file: "03-12"
                id: "12-reaching-agreement"
              - label: "**13.** Working together"
                file: "03-13"
                id: "13-working-together"
              - label: "**14.** Taking the long view"
                file: "03-14"
                id: "14-taking-the-long-view"
          - label: "Nurturing community"
            id: "4-nurturing-community"
            children: 
              - label: "**15.** A marriage of misfits"
                file: "04-15"
                id: "15-a-marriage-of-misfits"
              - label: "**16.** Gathering together"
                file: "04-16"
                id: "16-gathering-together"
              - label: "**17.** Once a fellow, always a fellow"
                file: "04-17"
                id: "17-once-a-fellow-always-a-fellow"
          - label: "Funding the future"
            id: "5-funding-the-future"
            children: 
              - label: "**18.** The $5m challenge"
                file: "05-18"
                id: "18-the-$5m-challenge"
          - label: "Epilogue"
            id: "6-epilogue"
            children: 
              - label: "**19.** Shades of green"
                file: "06-19"
                id: "19-shades-of-green"
          - label: "Appendix"
            children:
              - label: "Overview"
                file: "50-01-appendix"
                id: "overview"
              - label: "**i.** Application form"
                file: "50-01-appendix"
                id: "i-application-form"
              - label: "**ii.** The agreement letter"
                file: "50-01-appendix"
                id: "ii-the-agreement-letter"
              - label: "**iii.** Open requirements"
                file: "50-01-appendix"
                id: "iii-open-requirements"
              - label: "**iv.** Open Locks"
                file: "50-01-appendix"
                id: "iv-open-locks"
              - label: "**v.** Gathering guidelines"
                file: "50-01-appendix"
                id: "v-gathering-guidelines"
              - label: "**vi.** Thou shalt scale sustainably"
                file: "50-01-appendix"
                id: "vi-though-shalt-scale-sustainably"
          - label: "References"
            file: "50-02-references"
        start-page: "0-3-contents" # At which file should users start reading?
        contents-page: "0-3-contents" # Your contents-page file, if you have one.
      epub:
        date: "" # YYYY-MM-DD e.g. publication date or last revision
        format: "Digital download" # e.g. Paperback, Digital download, Digital online
        identifier: "" # e.g. ISBN or UUID
        image: "cover.jpg"
        start-page: "0-3-contents"
        contents-page: "0-3-contents"
        files: # add a value to any file to set any of the guide types listed in http://www.idpf.org/epub/20/spec/OPF_2.0.1_draft.htm#Section2.6
          - "0-0-cover": "cover"
          - "0-1-titlepage": "title-page"
          - "0-2-copyright": "copyright-page"
          - "0-3-contents": "toc"
          - "01": "text"
          - "02"
        toc: # For each menu item, include at least label and file (epub requires file). Optionally add id (for deep linking) and children.
          - label: "Cover"
            file: "0-0-cover"
          - label: "Title page"
            file: "0-1-titlepage"
          - label: "Copyright"
            file: "0-2-copyright"
          - label: "Contents"
            file: "0-3-contents"
          - label: "Chapter One"
            file: "01"
            id: "1-hello-world"
          - label: "Chapter Two"
            file: "02"
            id: "2-goodbye-world"
            children:
              - label: "Subsection"
                file: "02"
                id: "example-id"
      screen-pdf:
        date: "" # YYYY-MM-DD e.g. publication date or last revision
        format: "Digital download" # e.g. Paperback, Digital download, Digital online
        identifier: "" # e.g. ISBN or UUID
        image: "cover.jpg"
        files:
          - "0-0-cover"
          - "0-1-titlepage"
          - "0-2-copyright"
          - "0-3-contents"
          - "01"
          - "02"
      app:
        date: "" # YYYY-MM-DD e.g. publication date or last revision
        format: "Digital download" # e.g. Paperback, Digital download, Digital online
        identifier: "" # e.g. ISBN or UUID
        image: "cover.jpg"
        files:
          - "index"
          - "0-1-titlepage"
          - "0-2-copyright"
          - "0-3-contents"
          - "01": "Chapter One"
          - "02": "Chapter Two"
        nav: # For each menu item, include at least label and file. Optionally add id (for deep linking) and children.
          - label: "Frontmatter"
            children:
              - label: "Cover"
                file: "index"
              - label: "Title page"
                file: "0-1-titlepage"
              - label: "Copyright"
                file: "0-2-copyright"
          - label: "Contents"
            file: "0-3-contents"
          - label: "Chapter One"
            file: "01"
            id: "1-hello-world"
          - label: "Chapter Two"
            file: "02"
            id: "2-goodbye-world"
            children: 
              - label: "Subsection"
                file: "02"
                id: "example-id"
        start-page: "0-3-contents" # At which file should users start reading?
        contents-page: "0-3-contents" # Your contents-page file, if you have one.
 